# Generated by Django 4.2.4 on 2023-08-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets_tracking', '0002_alter_device_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField()),
                ('condition_when_checked_out', models.CharField(max_length=100)),
                ('condition_when_returned', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_tracking.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_tracking.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
