# Generated by Django 4.2.4 on 2023-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_tracking', '0009_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('Dead', 'Dead')], max_length=10, null=True),
        ),
    ]
